version: '3.0'

services:
  api:
    build:
      context: ./server
    env_file:
      - server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    command: npm start
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm start
  nginx:
    ports:
      - "3050:80"
    build:
      context: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api
      - client
    restart: always
